name: Download and Deploy

# Controls when the workflow will run
on: push

jobs:  
  get_asset:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
        repository: kaym9n/ROBOTIS-OP3-Demo
        run-id: 7581048488
        name: github-pages        
    - name: Display structure of downloaded files
      run: ls -al
        
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: get_asset
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
